[formatting]
  align_comments        = true
  align_entries         = true
  align_single_comments = true
  allowed_blank_lines   = 2
  array_trailing_comma  = true
  indent_entries        = true
  indent_tables         = true
  reorder_keys          = true
  trailing_newline      = true
